// Authentication error codes
export const ERROR_CODES = {
  // Authentication errors
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  NOT_AUTHENTICATED: "NOT_AUTHENTICATED",
  NO_TOKEN: "NO_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  // User errors
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",

  // Validation errors
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Server errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  NOT_FOUND: "NOT_FOUND",

  // OpenAI/External API errors
  OPENAI_API_ERROR: "OPENAI_API_ERROR",
  OPENAI_RATE_LIMIT: "OPENAI_RATE_LIMIT",
  OPENAI_AUTHENTICATION_ERROR: "OPENAI_AUTHENTICATION_ERROR",
  OPENAI_CONNECTION_ERROR: "OPENAI_CONNECTION_ERROR",
  OPENAI_TIMEOUT_ERROR: "OPENAI_TIMEOUT_ERROR",
  OPENAI_INVALID_RESPONSE: "OPENAI_INVALID_RESPONSE",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
